### ISSUE TITLE
Windows compatibility

### ISSUE THREAD

**Issue by naholyr** [tiaanduplessis/kill-port#3]
One of the main interest of a version written in node is to be cross-platform ;) wouldn't it be interesting to implement a Windows-compatible command? Cf. https://stackoverflow.com/questions/39632667/how-to-kill-a-currently-using-port-on-localhost-in-windows

**Comment by StephanBijzitter** [comment]
This is exactly what I was searching for in a project that (sadly) has to support windows.

**Comment by tiaanduplessis** [comment]
@naholyr @StephanBijzitter please check v1.2.0

**Comment by StephanBijzitter** [comment]
Will be able to do that this weekend! :-)

**Comment by naholyr** [comment]
Well done!

**Comment by liuliangsir** [comment]
Same issue here.
Here are some error informations.
> let port = args.port ? args.port.split(',') : args.unknown`

**Comment by jacklovepdf** [comment]
not work on windows

**Comment by fabiantoth** [comment]
Does not work in windows, should state that in install docs

**Comment by tiaanduplessis** [comment]
Should be resolved with #34

**Comment by tiaanduplessis** [comment]
Should be fixed in 1.6.0

**Comment by NeliHarbuzava** [comment]
Does not work on windows 10 pro. Promise nor resolves, nor rejects.

**Comment by NeliHarbuzava** [comment]
I found out that if I try to run in PowerShell command which program compiles for win32 (index.js:13) it never finishes. For example command `netstat -ao | findStr TCP.*:50159`. However if I'll add n flag to it, the command finishes successfully `netstat -nao | findStr TCP.*:50159`.

So it seems is there some poblem with netstat flags?

**Comment by NeliHarbuzava** [comment]
Also I may suggest to kill processes on windows with `/F` flag (forcefully). I found if I use example from readme to start server and kill process on port, sometimes calling kill-port gives me an error:

```
ERROR: The process with PID 8852 could not be terminated.
Reason: This process can only be terminated forcefully (with /F option).
PS C:\Users\User> taskkill /F /PID 8852
```

I am not very aware about Windows internals about processes and why this happens sometimes. Open to discussion.

**Comment by baumatron** [comment]
Related to @NeliHarbuzava's finding, netstat on my machine can take around 70 seconds to complete with the `-ao` flags. Changing this to `-nao` to avoid trying to resolve host names (which is not needed) makes the command run much faster.

**Comment by baumatron** [comment]
It seems now with netstat that processes with client socket ports that match the remote address are also killed, which wasn't the prior behavior. I assume the intent is to only kill a process that is listening on a given port.
```
PS D:\> netstat -nao | select-string 9229

  TCP    127.0.0.1:9229         0.0.0.0:0              LISTENING       7232
  TCP    127.0.0.1:9229         127.0.0.1:52671        ESTABLISHED     7232
  TCP    127.0.0.1:52660        127.0.0.1:9229         TIME_WAIT       0
...
  TCP    127.0.0.1:52671        127.0.0.1:9229         ESTABLISHED     18892
...
  TCP    [::1]:52784            [::1]:9229             SYN_SENT        18892
  TCP    [::1]:52785            [::1]:9229             SYN_SENT        18892
```
`18892` in this case is a client debugger process which shouldn't be affected by `kill-port`. In other words only an entry with `LISTENING` should be killed, which is also the only entry with the specified port in the 'local address' column on the left. The other is a remote address that the debugger is connected to.

Output from the prior command:
```
PS D:\> Get-NetTCPConnection -LocalPort 9229

LocalAddress                        LocalPort RemoteAddress                       RemotePort State       AppliedSetting OwningProcess
------------                        --------- -------------                       ---------- -----       -------------- -------------
127.0.0.1                           9229      127.0.0.1                           52671      Established Internet       7232
127.0.0.1                           9229      0.0.0.0                             0          Listen                     7232
```
