### ISSUE TITLE
Quite slow on Windows

### ISSUE THREAD

**Issue by StephanBijzitter** [tiaanduplessis/kill-port#43]
While it works, it's quite slow on Windows for me. I was tinkering with the source code a bit and found that changing `netstat -ao` into `netstat -aon` makes it significantly faster. On my laptop for example, it's about 10 seconds faster.

I know basically nothing about netstat though, so there may be a really good reason why `-n` isn't used... but just in case it's an oversight, here's the heads-up :-)

**Comment by seahindeniz** [comment]
@tiaanduplessis do you have plans for releasing the latest changes on this repository? 
Changes in #39 has the fix for this issue

**Comment by tiaanduplessis** [comment]
Should be resolved in 1.6.1
