### ISSUE TITLE
PID cannot be terminated unless forcefully with /F option

### ISSUE THREAD

**Issue by Inventsable** [tiaanduplessis/kill-port#44]
Trying to kill an ExpressJS server instance (in JS, not CLI) because my Hot Reloading app causes it to duplicate listen messages, and am getting this error on `kill` command:

```
cmd: TaskKill /PID 28236",
code: 1,
stderr: "ERROR: The process with PID 28236 could not be terminated.
Reason: This process can only be terminated forcefully (with /F option).",
stdout:""
```

Don't see any means to add flags to the `kill` method. Is there a solution to this?

**Comment by tiaanduplessis** [comment]
Hi @Inventsable . What version of the package are you using?

**Comment by tiaanduplessis** [comment]
Closing for now. Please reopen if the issue persists.
