### ISSUE TITLE
Fail when no processes found?

### ISSUE THREAD

**Issue by alexanderankin** [tiaanduplessis/kill-port#53]
Willing to work on this, want to confirm/discuss before a PR though.

**Comment by OXXXRA** [comment]
It's PR resolve this problem:
https://github.com/tiaanduplessis/kill-port/pull/59

**Comment by segfault79** [comment]
Useful fix. Any progress here? Can you merge this to master please @tiaanduplessis ?

**Comment by tiaanduplessis** [comment]
@segfault79 will do 👍🏻

**Comment by tiaanduplessis** [comment]
Should be resolved with `v2.0.0`
